# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import agent_platform_pb2 as agent__platform__pb2


class AgentServiceStub(object):
    """Agent Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_unary(
                '/agentplatform.AgentService/ExecuteTask',
                request_serializer=agent__platform__pb2.TaskRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.TaskResponse.FromString,
                )
        self.StreamTask = channel.unary_stream(
                '/agentplatform.AgentService/StreamTask',
                request_serializer=agent__platform__pb2.TaskRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.TaskChunk.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/agentplatform.AgentService/GetStatus',
                request_serializer=agent__platform__pb2.StatusRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.StatusResponse.FromString,
                )
        self.RegisterAgent = channel.unary_unary(
                '/agentplatform.AgentService/RegisterAgent',
                request_serializer=agent__platform__pb2.AgentInfo.SerializeToString,
                response_deserializer=agent__platform__pb2.RegistrationResponse.FromString,
                )
        self.ListAgents = channel.unary_unary(
                '/agentplatform.AgentService/ListAgents',
                request_serializer=agent__platform__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.ListAgentsResponse.FromString,
                )


class AgentServiceServicer(object):
    """Agent Service Definition
    """

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=agent__platform__pb2.TaskRequest.FromString,
                    response_serializer=agent__platform__pb2.TaskResponse.SerializeToString,
            ),
            'StreamTask': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTask,
                    request_deserializer=agent__platform__pb2.TaskRequest.FromString,
                    response_serializer=agent__platform__pb2.TaskChunk.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=agent__platform__pb2.StatusRequest.FromString,
                    response_serializer=agent__platform__pb2.StatusResponse.SerializeToString,
            ),
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=agent__platform__pb2.AgentInfo.FromString,
                    response_serializer=agent__platform__pb2.RegistrationResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=agent__platform__pb2.ListAgentsRequest.FromString,
                    response_serializer=agent__platform__pb2.ListAgentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentplatform.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Agent Service Definition
    """

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentplatform.AgentService/ExecuteTask',
            agent__platform__pb2.TaskRequest.SerializeToString,
            agent__platform__pb2.TaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/agentplatform.AgentService/StreamTask',
            agent__platform__pb2.TaskRequest.SerializeToString,
            agent__platform__pb2.TaskChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentplatform.AgentService/GetStatus',
            agent__platform__pb2.StatusRequest.SerializeToString,
            agent__platform__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentplatform.AgentService/RegisterAgent',
            agent__platform__pb2.AgentInfo.SerializeToString,
            agent__platform__pb2.RegistrationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentplatform.AgentService/ListAgents',
            agent__platform__pb2.ListAgentsRequest.SerializeToString,
            agent__platform__pb2.ListAgentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ToolServiceStub(object):
    """Tool Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTool = channel.unary_unary(
                '/agentplatform.ToolService/ExecuteTool',
                request_serializer=agent__platform__pb2.ToolRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.ToolResponse.FromString,
                )
        self.ListTools = channel.unary_unary(
                '/agentplatform.ToolService/ListTools',
                request_serializer=agent__platform__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.ListToolsResponse.FromString,
                )
        self.RegisterTool = channel.unary_unary(
                '/agentplatform.ToolService/RegisterTool',
                request_serializer=agent__platform__pb2.ToolInfo.SerializeToString,
                response_deserializer=agent__platform__pb2.RegistrationResponse.FromString,
                )


class ToolServiceServicer(object):
    """Tool Service Definition
    """

    def ExecuteTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=agent__platform__pb2.ToolRequest.FromString,
                    response_serializer=agent__platform__pb2.ToolResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=agent__platform__pb2.ListToolsRequest.FromString,
                    response_serializer=agent__platform__pb2.ListToolsResponse.SerializeToString,
            ),
            'RegisterTool': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTool,
                    request_deserializer=agent__platform__pb2.ToolInfo.FromString,
                    response_serializer=agent__platform__pb2.RegistrationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentplatform.ToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ToolService(object):
    """Tool Service Definition
    """

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentplatform.ToolService/ExecuteTool',
            agent__platform__pb2.ToolRequest.SerializeToString,
            agent__platform__pb2.ToolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentplatform.ToolService/ListTools',
            agent__platform__pb2.ListToolsRequest.SerializeToString,
            agent__platform__pb2.ListToolsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentplatform.ToolService/RegisterTool',
            agent__platform__pb2.ToolInfo.SerializeToString,
            agent__platform__pb2.RegistrationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class TaskWorkerStub(object):
    """Task Worker Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessTask = channel.unary_unary(
                '/agentplatform.TaskWorker/ProcessTask',
                request_serializer=agent__platform__pb2.TaskRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.TaskResponse.FromString,
                )
        self.GetTaskStatus = channel.unary_unary(
                '/agentplatform.TaskWorker/GetTaskStatus',
                request_serializer=agent__platform__pb2.TaskStatusRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.TaskStatusResponse.FromString,
                )
        self.ListWorkers = channel.unary_unary(
                '/agentplatform.TaskWorker/ListWorkers',
                request_serializer=agent__platform__pb2.ListWorkersRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.ListWorkersResponse.FromString,
                )


class TaskWorkerServicer(object):
    """Task Worker Service
    """

    def ProcessTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessTask,
                    request_deserializer=agent__platform__pb2.TaskRequest.FromString,
                    response_serializer=agent__platform__pb2.TaskResponse.SerializeToString,
            ),
            'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatus,
                    request_deserializer=agent__platform__pb2.TaskStatusRequest.FromString,
                    response_serializer=agent__platform__pb2.TaskStatusResponse.SerializeToString,
            ),
            'ListWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkers,
                    request_deserializer=agent__platform__pb2.ListWorkersRequest.FromString,
                    response_serializer=agent__platform__pb2.ListWorkersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentplatform.TaskWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskWorker(object):
    """Task Worker Service
    """

    @staticmethod
    def ProcessTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentplatform.TaskWorker/ProcessTask',
            agent__platform__pb2.TaskRequest.SerializeToString,
            agent__platform__pb2.TaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentplatform.TaskWorker/GetTaskStatus',
            agent__platform__pb2.TaskStatusRequest.SerializeToString,
            agent__platform__pb2.TaskStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentplatform.TaskWorker/ListWorkers',
            agent__platform__pb2.ListWorkersRequest.SerializeToString,
            agent__platform__pb2.ListWorkersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
